name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller
        shell: pwsh
      - name: Build executable
        run: python -m PyInstaller app/main.py --name vinted-assistant --noconfirm --onefile --clean
        shell: pwsh
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: vinted-assistant
          path: dist/**
