name: Windows Build

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pytest

      - name: Run tests
        run: |
          pytest

      - name: Build Windows executable
        run: |
          python -m PyInstaller app/main.py \
            --name vinted-assistant \
            --onefile \
            --clean

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vinted-assistant-windows
          path: dist/vinted-assistant.exe
          if-no-files-found: error
